### ISSUE TITLE
Is there an explanation to why it is so painful to setup this dataset ?

### ISSUE THREAD

**Issue by valentin-fngr** [EricGuo5513/HumanML3D#116]
Hi, 

I am new to the field and desires to work on that solving motion to text problems. 

I am probably asking a very trivial question : Why is it so painful to setup everything ? 
What can be done to simplify this process ? It seems like a lot of instructions are counter intuitive and do not seem to blend together, e.g : 

> Place all files under the directory **./amass_data/**. The directory structure shoud look like the following:  

vs 

> Download SMPL+H mode from [SMPL+H](https://mano.is.tue.mpg.de/download.php) (choose Extended SMPL+H model used in AMASS project) and [DMPL](https://smpl.is.tue.mpg.de/download.php) model from DMPL (choose DMPLs compatible with SMPL). Then place all the models under "./body_model/".

it seems like no one seem to be bothered by the entire complexity to just setup this project. 

Please let me know, I might be missing something

**Comment by EricGuo5513** [comment]
Hi, I understand that it's quite cumbersome to go through these pipelines. That's because humanml3D uses the motion data from various datasets which are under different distribution license. Please note capturing 3d motion data is an VERY expensive and laborious process. Every dataset creator pays a lot of effort on this. We can not distribute them as our own data, even SMPL-H/DMPL models. Therefore, we request everyone to download the motion data and body models from their source website, and comply the license.

**Comment by valentin-fngr** [comment]
Makes sense, thank you for clarification. I was not aware that the process of capturing 3D motion was so expensive. 
Last question : is it the sensor, the time involved, or the post processing of the data captured that makes it expensive ?

**Comment by EricGuo5513** [comment]
Hi, usually there will be a room, a suit with sensors, paid actors to
perform actions, and a professional to do all the calibration. After that,
people process the captured data and fit SMPL models for them.
