### ISSUE TITLE
data leakage in cal_mean_variance.ipynb

### ISSUE THREAD

**Issue by Sy-Zhang** [EricGuo5513/HumanML3D#28]
It seems like `cal_mean_variance.ipynb` computes mean and variance on all data, which leads data leakage since test data is used.

**Comment by EricGuo5513** [comment]
Thanks, I think you make a point here. This can be a potential problem. But I feel it is actually quite minor. Because the mean and variance can not leak much information. In contrast, if we compute mean/variance on validation/test/train set respectively, it can be detrimental to small set, for example KIT-ML. Because of the small size of subset, the mean/variance is not very accurate. Therefore, we can regard it as a tradeoff probably.

**Comment by Sy-Zhang** [comment]
> Thanks, I think you make a point here. This can be a potential problem. But I feel it is actually quite minor. Because the mean and variance can not leak much information. In contrast, if we compute mean/variance on validation/test/train set respectively, it can be detrimental to small set, for example KIT-ML. Because of the small size of subset, the mean/variance is not very accurate. Therefore, we can regard it as a tradeoff probably.

Thanks for answering!
