### ISSUE TITLE
Necessary to use IK

### ISSUE THREAD

**Issue by shunlinlu** [EricGuo5513/HumanML3D#66]
HI, Eric

Thanks for showing such great work.

I'm just wondering why you use Inverse Kinematics to get the local rotations. Amass provides local rotations, doesn't it? Or it is because Humanact12 does not provide any rotation data. @EricGuo5513 

Thanks 
Shunlin

**Comment by EricGuo5513** [comment]
Hi,

It is mostly because we need to adjust the rotations and position to make
them, for example, initially facing Z+ directions and foot on floor. It
should be more convenient to do that in 3D positions. After that, we use IK
to re-obtain location rotations.

Best,

Chuan

**Comment by shunlinlu** [comment]
Thanks for your reply.

**Comment by yt4766269** [comment]
I still do not quite get the point. The local rotations in the AMASS dataset are not influenced by the global rotation and translation of the whole human body, isn't it?

**Comment by dj-kefir-siorbacz** [comment]
Sorry for necropost, but @EricGuo5513's argument is kinda weird. 
It's much easier to rotate the root and then do forward kinematics to obtain new 3D positions (either local or global), than to rotate global positions and then do IK do get the local rotations.

**Comment by kai-lan** [comment]
My guess is unlike Mocap data, AMASS data do not come with uniform offsets. For example, two people can have different offsets. In order to retarget all motions from different people to a uniform skeleton with fixed offsets, you would have to find global joint positions for each motion, and run inverse kinematics to obtain joint rotations.
